ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:
endif::[]

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/antora-supplemental/antora-build-action/graphs/contributors"><img src="https://img.shields.io/github/contributors/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/network/members"><img src="https://img.shields.io/github/forks/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/stargazers"><img src="https://img.shields.io/github/stars/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/issues"><img src="https://img.shields.io/github/issues/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">Antora Site Builder</h3>
<p align="center">
GitHub Action to build Antora documentation sites with support for private repos, multi-repo aggregation, and extensions.<br />
<a href="https://antora-supplemental.github.io/antora-build-action/"><strong>Explore the docs ·</strong></a>
<br /><br />
<a href="https://github.com/antora-supplemental/antora-build-action/issues">Report Bug</a>
&middot;
<a href="https://github.com/antora-supplemental/antora-build-action/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/antora-supplemental/antora-build-action/graphs/contributors"><img src="https://img.shields.io/github/contributors/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/network/members"><img src="https://img.shields.io/github/forks/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/stargazers"><img src="https://img.shields.io/github/stars/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/issues"><img src="https://img.shields.io/github/issues/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">Antora Site Builder</h3>
<p align="center">
GitHub Action to build Antora documentation sites with support for private repos, multi-repo aggregation, and extensions.<br />
<a href="https://antora-supplemental.github.io/antora-build-action/"><strong>Explore the docs ·</strong></a>
<br /><br />
<a href="https://github.com/antora-supplemental/antora-build-action/issues">Report Bug</a>
&middot;
<a href="https://github.com/antora-supplemental/antora-build-action/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/antora-supplemental/antora-build-action/graphs/contributors"><img src="https://img.shields.io/github/contributors/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/network/members"><img src="https://img.shields.io/github/forks/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/stargazers"><img src="https://img.shields.io/github/stars/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/antora-supplemental/antora-build-action/issues"><img src="https://img.shields.io/github/issues/antora-supplemental/antora-build-action.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">Antora Site Builder</h3>
<p align="center">
GitHub Action to build Antora documentation sites with support for private repos, multi-repo aggregation, and extensions.<br />
<a href="https://antora-supplemental.github.io/antora-build-action/"><strong>Explore the docs ·</strong></a>
<br /><br />
<a href="https://github.com/antora-supplemental/antora-build-action/issues">Report Bug</a>
&middot;
<a href="https://github.com/antora-supplemental/antora-build-action/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/antora-supplemental/antora-build-action.svg?style=for-the-badge[Contributors,link=https://github.com/antora-supplemental/antora-build-action/graphs/contributors]
image:https://img.shields.io/github/forks/antora-supplemental/antora-build-action.svg?style=for-the-badge[Forks,link=https://github.com/antora-supplemental/antora-build-action/network/members]
image:https://img.shields.io/github/stars/antora-supplemental/antora-build-action.svg?style=for-the-badge[Stars,link=https://github.com/antora-supplemental/antora-build-action/stargazers]
image:https://img.shields.io/github/issues/antora-supplemental/antora-build-action.svg?style=for-the-badge[Issues,link=https://github.com/antora-supplemental/antora-build-action/issues]

= Antora Site Builder

GitHub Action to build Antora documentation sites with support for private repos, multi-repo aggregation, and extensions.

link:https://antora-supplemental.github.io/antora-build-action/[Explore the docs] ·
link:https://github.com/antora-supplemental/antora-build-action/issues[Report Bug] ·
link:https://github.com/antora-supplemental/antora-build-action/issues[Request Feature]
endif::[]

== About The Project

The **full manual** (multi-page, Antora-generated) is published here:

https://antora-supplemental.github.io/antora-build-action/

AsciiDoc sources and the Antora playbook live in the `docs/` directory of this repository.

The https://github.com/marketplace[GitHub Marketplace] listing is generated from `README.md` only.

Pair with `upload-pages-artifact` and `deploy-pages` for GitHub Pages deployment.

++++
<p align="right">(<a href="#readme-top">back to top</a>)</p>
++++
== Contact

Antora Supplemental — support@antora-supplemental.org

* Project: https://github.com/antora-supplemental/antora-build-action
* Site: https://antora-supplemental.org

++++
<p align="right">(<a href="#readme-top">back to top</a>)</p>
++++